chore(repos): change to `--config` like pacman
Signed-off-by: h8d13 <hadean-eon-dev@proton.me>

diff --git a/aptac b/aptac
--- a/aptac
+++ b/aptac
@@ -53,7 +53,8 @@
 #
 #   deps PACKAGE [OPTIONS]          Show dependency tree (pactree)
 #
-#   repos [CONF]                    List repos from pacman.conf (enabled/disabled)
+#   repos [OPTIONS]                 List repos from pacman.conf (enabled/disabled)
+#       --config FILE               Read an alternate config (default /etc/pacman.conf)
 #
 #   update [OPTIONS]                Force-sync package databases (-Syy)
 #   upgrade [OPTIONS]               Full system upgrade (-Syu)
@@ -144,7 +145,19 @@ show_dependencies() {
 
 # Repository overview from pacman.conf: bare [repo] enabled, #[repo] disabled.
 list_repos() {
-	local conf="${1:-/etc/pacman.conf}"
+	local conf="/etc/pacman.conf"
+	while [[ $# -gt 0 ]]; do
+		case "$1" in
+		--config)
+			conf="$2"
+			shift 2
+			;;
+		*)
+			echo "error: unknown option '$1' (expected --config FILE)" >&2
+			return 1
+			;;
+		esac
+	done
 	if [[ ! -r "$conf" ]]; then
 		echo "error: cannot read $conf" >&2
 		return 1
